package com.mpr.db;

import java.io.IOException;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.Properties;

public class DBManager {
	
	private Connection connection;

	private Statement stmt;

	
	public DBManager() {
		Properties properties = new Properties();
		try {
			properties.load(ClassLoader.getSystemResourceAsStream("com/mpr/db/jdbc.properties"));		
			connection = DriverManager.getConnection(properties.getProperty("url"));
			stmt=connection.createStatement();		
			createTables();
					
		} catch (IOException e) {			
			e.printStackTrace();
		} catch (SQLException e) {			
			e.printStackTrace();
		}
	}
	
	
	private void createTables() throws SQLException{
		
			ResultSet result = connection.getMetaData().getTables(null, null, null, null);
			boolean storeHouseTableExists = false;
			boolean productTableExists = false;
			while(result.next()){
				String name = result.getString("TABLE_NAME");
				if(name.equals("storehouse")){
					storeHouseTableExists=true;
				}else if(name.equals("product")){
					productTableExists=true;
				}
			}
			if(!storeHouseTableExists){
				System.out.println("Creating storehouse table");
				stmt.executeUpdate("" +
						"CREATE TABLE storehouse(" +
						"id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY," +
						"name varchar(30))");
			}
			if(!productTableExists){
				System.out.println("Creating product table");
				stmt.executeUpdate("" +
						"CREATE TABLE product(" +
						"id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY," +
						"name varchar(30)," +
						"price decimal(10,2)," +
						"storehouse_id bigint, "+
						"FOREIGN KEY (storehouse_id) REFERENCES storehouse(id))");
									
			}
					
	}


	public Connection getConnection() {
		return connection;
	}
	
	
	
	

}
